name: weread

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: weread
        env:
          GIST_ID: ea4fa59c2eb06f3eb1ccff624f9ac28a
          GT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GT_USER: zhangkesheng
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
        run: go run ./main.go weread
