name: weread

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: weread
        run: go run ./main.go weread
